spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_configuration_manager
    username: ${DB_USERNAME:db_configuration_manager_admin}
    password: ${DB_PASSWORD:SNgCjskqMY8LqSvNZ_Y}
server:
  port: ${APPLICATION_PORT:9091}


logging:
  level:
    ru: info

springdoc:
  show-actuator: true
  swagger-ui:
    config-url: qwerty
#springdoc:
#  api-docs:
#    path: /v3/api-docs